"""Init

Revision ID: 0c553c61e3e6
Revises: 233aa49bc990
Create Date: 2022-12-21 10:28:47.875578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c553c61e3e6'
down_revision = '233aa49bc990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
